### ISSUE TITLE
Delete `README.Rmd`

### ISSUE THREAD

**Issue by rolyp** [layik/eAtlas#100]
`README.Rmd` is generated from `README.md` using `markdown::render`.  Since we are regularly updating `README.md` with installation/setup instructions, this is a bit of a pain.

- [x] <s>generate `.md` when `.Rmd` modified?</s>
  - [x] new `.git.hooks` folder for storing commit hooks in repo
  - [x] create `.git.hooks/pre-commit` and make executable
  - [x] symlink to `.git.hooks/pre-commit` from `.git/hooks`
  - [x] install `rmarkdown` into RStudio from CRAN
  - [x] <s>install `pandoc`</s> :x: `package ‘pandoc’ is not available for this version of R`
  - [x] lazy installation of required packages in `pre-commit`
- [x] [alternatively] delete `README.Rmd`

**Comment by layik** [comment]
Rmd generates .md and would like to keep it that way until something better comes up.

**Comment by rolyp** [comment]
@layik Got it. What is the process by which the .md is generated, btw?

**Comment by layik** [comment]
Sorry, also Rmd is good when we like to run some code as we generate the doc.
To build an Rmd a simple R [command](https://bookdown.org/yihui/rmarkdown/compile.html) of `rmarkdown::render("path/to/README.Rmd")` is enough, the rest is handled in the `yml` style document itself which sets out generating a `github_document` etc in our case.

**Comment by rolyp** [comment]
@layik I didn't really follow that explanation -- I'll add this topic to a meeting agenda and send a message on Slack to arrange a time.

**Comment by layik** [comment]
Apologies, will be clearer soon.

**Comment by rolyp** [comment]
@layik Given the complexity of the consolidation tasks we have identified, it would streamline things a bit if it were possible to edit `README.md` directly, rather than having to go via `README.Rmd`, at least if the only benefit of the current setup is the generation of a date. Shall we go ahead and switch to a directly edited `README.md` and delete the `.Rmd` version?

**Comment by layik** [comment]
I see the difficulty it is causing your @rolyp. Forgive me as I use pandoc etc on daily basis and did not feel those difficulties so leave it with me, I think Rmd causes some extra `\n`s other than that should be just a delete commit.

**Comment by rolyp** [comment]
It's not a major problem, but yes it seems like a fair amount of config/automation involved to set up a feature that we're not actually taking advantage of yet. (Although I now understand your point about how we could use the `.Rmd` to for example include code output into `README.md`. But until that becomes a requirement, perhaps it's better to simplify.)

**Comment by rolyp** [comment]
@layik No worries, easier for me to take care of as I'm working on this now.
