### ISSUE TITLE
Preserve API URL vars when mapview changes

### ISSUE THREAD

**Issue by layik** [layik/eAtlas#113]
Include this in share button.

**Comment by nbarlowATI** [comment]
This is now pretty much implemented in the `preserve-defaultURL` branch:
* `defaultURL`, `geographyURL` and `geographyColumn` will (if not "undefined") be added to the search string of the URL.
* This is all done by modifying the `updateHistory` function in `utils.js` (with a slight modification in `Welcome.js` to pass these props to that function).
* Trying to figure out how to test this - the `history` object is not available in jest - looking into mocking it via `createMemoryHistory`.

**Comment by layik** [comment]
I agree. If you are happy with the minor changes @nbarlowATI feel free to PR the branch onto develop and merge.
