### ISSUE TITLE
Spatial view coordination

### ISSUE THREAD

**Issue by rolyp** [layik/eAtlas#133]
The various views on the left need to be coordinated with (linked to) the map view, i.e. re-queried/re-rendered when the data selection changes. For now we will just consider this to be when the map view is panned or zoomed and “subset based on map bounds” is checked.

Solve the following infrastructure problems first: 
- tgve/app#47
- tgve/app#48

Then:
- [x] where is “subset based on map bounds” checkbox? ➡️ Tab 2 of `Decksidebar.jsx`
- [x] snapshot test for filtering based on `accident_severity`
  - [x] load `casualties_100` data set
  - [x] select `span` containing `Slight` text
    - [x] generalise `waitForElementText` to wait until there is at least one element matching query
  - [x] click on  `div` containing `Slight` span    
    - [x] locate `span` with text content `Slight` using `waitForXPath`
    - [x] click on parent `div` element
  - <s>instead of simulating mouse events for selection, add `&select=accident_severity:Slight` to URL instead</s>
- [ ] Puppeteer tests no longer running in GitHub Actions?
- [x] extract `filterData` function from `_generateLayer` 
- [x] extensive tests needs to be done but looks ok!

**Comment by layik** [comment]
Just to clarify, everything in tgvejs is based on `filtered` and `unfiltered` data, including tooltip. So
> The various views on the left need to be coordinated with (linked to) the map view, i.e. re-queried/re-rendered when the data selection changes.

is implemented. The critical part in this is throttling which is done for updating URLs here:
https://github.com/tgve/tgvejs/blob/7aa3ae089952dd4612e18918cfb480eea90608c5/src/Welcome.js#L584

What we need to do, is:
1. find space where the "clip"ing happens. We already get the bounding box [here](https://github.com/tgve/tgvejs/blob/7aa3ae089952dd4612e18918cfb480eea90608c5/src/Welcome.js#L588)
2. use either [this](https://www.npmjs.com/package/@turf/bbox-clip) or custom function
3. regenerate layer

That is sufficient for "left side" or "sidebar" as they are linked views.

**Comment by layik** [comment]
Should also say this
https://github.com/tgve/tgvejs/blob/7aa3ae089952dd4612e18918cfb480eea90608c5/src/Welcome.js#L589

belongs to the master branch days.

**Comment by rolyp** [comment]
Thanks @layik, will try to understand some of this tomorrow.

**Comment by layik** [comment]
I have started this and sp far so good. Will push as and when

**Comment by layik** [comment]
Checklist above was before #147 etc

**Comment by layik** [comment]
Might need to bring subset checkbox into tab1 for usability reasons

**Comment by layik** [comment]
Todo:

- [x] ~turf `booleanContains` seems to be very slow~
- [x] sync checkbox with home

**Comment by layik** [comment]
Aware of branch https://github.com/tgve/tgvejs/tree/subset-mapbounds

**Comment by layik** [comment]
![Peek 2022-03-27 11-21](https://user-images.githubusercontent.com/408568/160277078-66635848-3ca2-4064-8f09-16fbd2016b86.gif)

**Comment by layik** [comment]
Hi @rolyp. Could you please check the check list item of puppeteer and of course the branch. Might be ready for a PR. Thank you.

**Comment by layik** [comment]
Lines/path data to test https://raw.githubusercontent.com/tgve/example-data/main/rnet/atumie.geojson
