### ISSUE TITLE
Delete `npm-tgver` and `tgver` branches

### ISSUE THREAD

**Issue by rolyp** [layik/eAtlas#98]
@layik Looks like this differs from `npm` by a single commit (https://github.com/tgve/eAtlas/commit/5b3535dea57cae54c6b2fae3c0aafbbf706a20ea) which removes the `plotly` dependency:

Need to figure out if this still needed and if so, whether there is a better solution to having another active branch.

**Comment by layik** [comment]
Indeed. The best way to close this ticket is for me to wait until next time I generate a build for `tgveR`, document exactly where this branch stands and then might be able to safely delete it.

**Comment by layik** [comment]
Alright, this needs documenting otherwise it is now clear that we need the branch to generate a build that can be submitted to CRAN. From Slack conversations:

> the npm package relies on plotlyjs as a package deps. This is way too heavy for CRAN (R repository) to accecpt, they accept max 5mb.
So far, the npm package is made with no/little <link /> tags so that people start using it.
That is why:
> 1. needed a branch on the npm package named npm-tgver without plotlyjs dependency and
> 2. Also needed a branch tgver on eatlas-template with <link /> for plotlyjs
> In order to get the R package bundled instance down to under 5mb

**Comment by rolyp** [comment]
@layik Btw, do we have a GitHub workflow that submits to CRAN? We could use such a thing to validate any proposed solution.

**Comment by layik** [comment]
`tgveR` is not submitted to CRAN yet, but even then I find CRAN volunteers to earn our cross-patform tests etc to be done manually rather than automated. I can ask others to see what they feel about submitting to CRAN automatically. One to discuss or keep as an open issue.

**Comment by rolyp** [comment]
Closing as duplicate of tgve/tgver#1.
